#!/bin/bash

CFGFILE=$1
SRC=$2
JOBNAME=$3
num_files=$4

flags=$5 # rest of the arguments

echo "CFGFILE="$CFGFILE
echo "SRC="$SRC
echo "JOBNAME="$JOBNAME
echo "num_files="$num_files
echo "flags="$flags

echo "Running cmsRun in local batch mode"
echo "Extra arguments to cmsRun:" $flags

if [ -d "$JOBNAME" ]; then
    echo "Directory "$JOBNAME" already exists"
    return
fi

mkdir $JOBNAME
total_lines=$(cat ${SRC} | wc -l)
((lines_per_file = (total_lines + num_files - 1) / num_files))

split -l ${lines_per_file} ${SRC} ${JOBNAME}'/job_'

for file in $JOBNAME/job_*
do
    cmsRun ${CFGFILE} inputFiles_load=${file} outputFile=${file}_out.root $flags &> ${file}.log &
done
echo "Called "$num_files" cmsRun jobs on input file "$SRC" with config "$CFGFILE
