#. ./util/bcmsRun runconfs/step2_MC_SIG_cfg.py fileLists/T_t.txt trees/T_t
#. ./util/bcmsRun runconfs/step2_MC_SIG_cfg.py fileLists/Tbar_t.txt trees/Tbar_t
#. ./util/bcmsRun runconfs/step2_MC_BKG_cfg.py fileLists/T_tW.txt trees/T_tW
#. ./util/bcmsRun runconfs/step2_MC_BKG_cfg.py fileLists/Tbar_tW.txt trees/Tbar_tW
#. ./util/bcmsRun runconfs/step2_MC_BKG_cfg.py fileLists/T_s.txt trees/T_s
#. ./util/bcmsRun runconfs/step2_MC_BKG_cfg.py fileLists/Tbar_s.txt trees/Tbar_s
#. ./util/bcmsRun runconfs/step2_MC_BKG_cfg.py fileLists/TTBar.txt trees/TTBar
. ./util/bcmsRun runconfs/step2_MC_BKG_cfg.py fileLists/WJets.txt trees/WJets
. ./util/bcmsRun runconfs/step2_MC_BKG_cfg.py fileLists/WW.txt trees/WW
. ./util/bcmsRun runconfs/step2_MC_BKG_cfg.py fileLists/WZ.txt trees/WZ
. ./util/bcmsRun runconfs/step2_MC_BKG_cfg.py fileLists/ZZ.txt trees/ZZ
